version: 2.1

orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@4.1.3
  aws-cloudformation: orbss/aws-cloudformation@0.1.6
  ansible-playbook: orbss/ansible-playbook@0.0.5
  ruby: circleci/ruby@2.1.3

jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml

#----CloudFormation(cfn)----
  execute-cfn:
    executor: aws-cloudformation/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - aws-cloudformation/deploy:
          stack-name: "lecture13-vpc"
          template-file-path: "cloudformation/lect13-vpc.yml"
      - aws-cloudformation/deploy:
          stack-name: "lecture13-ec2"
          template-file-path: "cloudformation/lect13-ec2.yml"
          capabilities: CAPABILITY_NAMED_IAM
      - aws-cloudformation/deploy:
          stack-name: "lecture13-s3"
          template-file-path: "cloudformation/lect13-s3.yml"
      - aws-cloudformation/deploy:
          stack-name: "lecture13-rds"
          template-file-path: "cloudformation/lect13-rds.yml"
      - aws-cloudformation/deploy:
          stack-name: "lecture13-alb"
          template-file-path: "cloudformation/lect13-alb.yml"
      - aws-cloudformation/deploy:
          stack-name: "lecture13-cw"
          template-file-path: "cloudformation/lect13-cw.yml"
          capabilities: CAPABILITY_NAMED_IAM

#----Get-variables-from-cfn----
  get-variables-from-cfn:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - run:  # Get values of EC2 Public IP, RDS Username, RDS Password, RDS Endpoint and ALB DNS Host, using AWS CLI
          #           echo '#!/bin/bash' >> env_vars.sh
          name: set environment variables
          command: |
            echo export EC2PublicIP=$(aws ec2 describe-instances --filters Name=tag:Name,Values=lecture13-ec2 --query Reservations[].Instances[].PublicIpAddress[] --output text) >> $BASH_ENV #env_vars.sh
            echo export RDSEndPoint=$(aws rds describe-db-instances --db-instance-identifier lecture13-rds --query DBInstances[].Endpoint[].Address[] --output text) >> $BASH_ENV #env_vars.sh
            echo export RDSUser=$(aws rds describe-db-instances --db-instance-identifier lecture13-rds --query DBInstances[].MasterUsername[] --output text) >> $BASH_ENV #env_vars.sh
            echo export RDSPass=$(aws ssm get-parameter --name /lecture13/rds-pass --with-decryption --query Parameter.Value --output text) >> $BASH_ENV #env_vars.sh
            echo export S3Name=$(aws cloudformation describe-stacks --stack-name lecture13-s3 --query Stacks[].Parameters[].ParameterValue[] --output text) >> $BASH_ENV #env_vars.sh
            echo export ALBDNSName=$(aws elbv2 describe-load-balancers --names lecture13-lb --query LoadBalancers[].DNSName[] --output text) >> $BASH_ENV #env_vars.sh
            cat $BASH_ENV #env_vars.sh
#      - persist_to_workspace:  #Share variables among jobs
#          root: .
#          paths:
#            - env_vars.sh

#----Ansible----
  execute-ansible:
    executor: ansible-playbook/default
    steps:
      - checkout
#      - attach_workspace:
#          at: .
      - run:
          name: check env_var.sh
          command: cat $BASH_ENV
#            source env_vars.sh
#            echo env_vars.sh >> $BASH_ENV

#ここで環境変数に追加できる?
# source env_vars.sh #runコマンドごとにパスを通さないといけない
# sed -i "s/EC2PublicIP/${EC2PublicIP}/g" ansible/inventory/target.yml
# sed -i "s/LoadBalancerDNSName/${LoadBalancerDNSName}/g" ansible/site.yml
# sed -i "s/RDSEndpoint/${RDSEndpoint}/g" ansible/site.yml
# sed -i "s/S3BucketName/${S3BucketName}/g" ansible/site.yml
#参考情報
# sed: ストリームエディタ。テキストを操作するためのコマンド。
# -i: インプレース編集。ファイルを直接編集するオプション。
# "s/EC2_PUBLIC_IP/${EC2_PUBLIC_IP}/g": 置換コマンド。
# s: 置換コマンドの開始。
# EC2_PUBLIC_IP: 置き換え対象の文字列。
# ${EC2_PUBLIC_IP}: 置き換え後の文字列（シェル変数の値）。
# /g: グローバルオプション。行全体で一致するすべてのインスタンスを置き換える。
      - add_ssh_keys:
          fingerprints:
            - ${KEY_FINGERPRINT}
      - ansible-playbook/install:
          version: 2.9.23
      - ansible-playbook/playbook:
          playbook: ansible/playbook.yml
          #playbook-options: -i ${AWS_EC2_IP}, --private-key ~/.ssh/ansible-test-key


#----Serverspec----
workflows:
  lecture13-workflow:
    jobs:
      #- cfn-lint
      #- execute-cfn:
      #    requires:
      #      - cfn-lint
      - get-variables-from-cfn
      #    requires:
      #      - execute-cfn
      - execute-ansible:
          requires:
            - get-variables-from-cfn
