version: 2.1

orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@4.1.3
  aws-cloudformation: orbss/aws-cloudformation@0.1.6

jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml

  execute-cfn:
    executor: aws-cloudformation/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - aws-cloudformation/deploy:
          stack-name: "lecture13-vpc"
          template-file-path: "cloudformation/lect13-vpc.yml"
      - aws-cloudformation/deploy:
          stack-name: "lecture13-ec2"
          template-file-path: "cloudformation/lect13-ec2.yml"
          capabilities: CAPABILITY_NAMED_IAM
      - aws-cloudformation/deploy:
          stack-name: "lecture13-s3"
          template-file-path: "cloudformation/lect13-s3.yml"
      - aws-cloudformation/deploy:
          stack-name: "lecture13-rds"
          template-file-path: "cloudformation/lect13-rds.yml"
      - aws-cloudformation/deploy:
          stack-name: "lecture13-alb"
          template-file-path: "cloudformation/lect13-alb.yml"
      - aws-cloudformation/deploy:
          stack-name: "lecture13-cw"
          template-file-path: "cloudformation/lect13-cw.yml"

workflows:
  lecture13-workflow:
    jobs:
      - cfn-lint
      - execute-cfn:
          requires:
            - cfn-lint
