---
all:
  hosts:
    webserver:
      ansible_host: ec2_publicip #To be replaced
      ansible_user: ec2-user
      ansible_port: 22
      ansible_ssh_private_key_file: ~/.ssh/Raisetech-AWS-Kadai-pem #id_rsa
      #ansible_ssh_private_key_file: "/home/taka0404/aws-ec2-pem/.ssh/Raisetech-AWS-Kadai-pem.pem"  #For local access
