- name: playroles
  hosts: webserver
  become: yes
  become_user: ec2-user
  gather_facts: true
  roles:
    - yum
    - mysql
    - git
    - anyenv
    - bundler
    - rails
    - yarn
    - image_magick
    - sample_app
    - systemd
    - nginx
    - aws_storage

  vars:
   - aws_rds_host: rds_endpoint  #To be replaced
   - aws_rds_user: rds_user  #To be replaced
   - aws_rds_pass: rds_pass  #To be replaced
   - aws_s3: s3_name  #To be replaced
   - aws_alb_dns : alb_dnsname  #To be replaced
