---
- name: playroles
  hosts: webserver
  become: yes
  become_user: ec2-user
  gather_facts: true
  roles:
    - yum
    #- mysql
    #- git
    #- anyenv
    #- bundler
    #- rails
    #- yarn
    #- image_magick
    #- sample_app
    #- systemd
    #- nginx
    #- aws_storage

  vars:
   - aws_rds_host: rds_endpoint #${RDSEndPoint} #lecture10-rdb.cpi2kykm2rye.ap-northeast-1.rds.amazonaws.com
   - aws_rds_user: rds_user #${RDSUser} #admin
   - aws_rds_pass: rds_pass #${RDSPass} #password
   - aws_s3: s3_name #${S3Name} #lecture10-s3
   - aws_alb_dns : alb_dnsname #${ALBDNSName} #13.115.99.211
